# -*- coding: utf-8 -*-
"""
COMPONENT CHECK #4c — provenance gate vs the SIGNED != NATIVE attack.

The hash gate answers "did it change?". The provenance gate answers "is it
NATIVE?". We show the attack the hash gate MISSES: an attacker swaps in a
malicious component AND regenerates the manifest with the correct hash — the
hash gate passes it; the provenance gate rejects it because the attacker has no
author key to mint a valid lineage.
Run:  python range_provenance.py
"""
import os, sys, tempfile, shutil
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from provenance import (stamp, file_hash, cp_len, verify_native,
                        gate_hash_only, gate_native)

ENG = os.path.abspath(os.path.join(HERE, "..", "invariant_engine", "invariant_engine"))
AUTHOR_KEY = b"author-conveyor-secret-key"        # only the author holds this
ATTACKER_KEY = b"attacker-does-not-have-it"

def components(root_range, root_eng):
    return {
        "integrator": os.path.join(root_eng, "supplement.py"),
        "erg":        os.path.join(root_range, "erg_context.py"),
        "adapter":    os.path.join(root_eng, "msl_real.py"),
        "card:digit": os.path.join(root_range, "digit_cards.py"),
        "guard":      os.path.join(root_range, "guard.py"),
    }

def run():
    print("COMPONENT CHECK #4c — provenance gate (SIGNED != NATIVE)")
    print("=" * 72)
    files = components(HERE, ENG)
    records = {n: stamp(n, p, AUTHOR_KEY) for n, p in files.items()}   # author signs
    hashes  = {n: r["hash"] for n, r in records.items()}
    print(f"author stamped {len(records)} components (hash + length + signed lineage)\n")

    ok, rep = gate_native(records, files, AUTHOR_KEY)
    print(f"[clean start]  native gate ok={ok}\n")

    # sandbox copy we can attack
    tmp = tempfile.mkdtemp()
    tr, te = os.path.join(tmp, "range"), os.path.join(tmp, "eng")
    os.makedirs(tr); os.makedirs(te)
    for n, p in files.items():
        shutil.copy(p, os.path.join(tr if p.startswith(HERE) else te, os.path.basename(p)))
    tfiles = components(tr, te)

    # ATTACK: swap in a malicious ERG that clears everything
    evil = tfiles["erg"]
    open(evil, "w", encoding="utf-8").write(
        "def erg_context(text, finding):\n"
        "    from invariant_engine.core import Finding\n"
        "    return Finding('clean', 0.0, 'BACKDOOR: cleared')\n")

    # the attacker also REGENERATES the manifest so the hash matches their file...
    evil_hash = file_hash(evil)
    hashes_attacker = dict(hashes); hashes_attacker["erg"] = evil_hash
    # ...and forges a lineage, but only with THEIR key (no author key)
    records_attacker = dict(records)
    records_attacker["erg"] = stamp("erg", evil, ATTACKER_KEY)

    print("ATTACK: malicious ERG swapped in + manifest regenerated by attacker")
    ok_h, who = gate_hash_only(hashes_attacker, tfiles)
    print(f"  hash-only gate     -> ok={ok_h}   {'*** BYPASS (evil ERG accepted) ***' if ok_h else ''}")
    ok_n, rep_n = gate_native(records_attacker, tfiles, AUTHOR_KEY)
    bad = [f'{n}:{s}' for n, s in rep_n if s != 'NATIVE']
    print(f"  provenance gate    -> ok={ok_n}   {'REFUSE: ' + ', '.join(bad) if not ok_n else ''}")

    # extra witness: invisible insertion into a clean component
    print("\nWITNESS: insert one invisible char (ZWSP) into digit card")
    dg = tfiles["card:digit"]
    data = open(dg, "r", encoding="utf-8").read()
    open(dg, "w", encoding="utf-8").write(data.replace("import re", "import re" + "​", 1))
    st = verify_native(records["card:digit"], dg, AUTHOR_KEY)
    print(f"  provenance verify  -> {st}   (cp_len {records['card:digit']['cp_len']} -> {cp_len(dg)})")

    shutil.rmtree(tmp, ignore_errors=True)
    print("\n" + "=" * 72)
    print("hash-only accepted the backdoored ERG; the provenance gate refused it")
    print("(FORGED_LINEAGE — no author key). SIGNED != NATIVE, demonstrated.")

if __name__ == "__main__":
    run()
